### PR TITLE
rename: _build -> _sources

### PR DESCRIPTION
**Pull request by blaggacao**
It just would look nicer:

https://github.com/divnix/devos/tree/6343a118ca26f4dd25e70dbb1a6cdf742007c32a/pkgs

### CODE REVIEW

**Comment by berberman** [comment]
Thank you, it makes sense. Please update the .gitignore and CI as well

**Comment by blaggacao** [comment]
> Please update the .gitignore and CI as well

Thx. `rg` filtered them hahahah. Done.

**Comment by berberman** [comment]
BTW, there's a typo in your commit message and PR title :P

**Comment by blaggacao** [comment]
@berberman Thanks, fixed. No excuse for this. :smile:

**Pull request merged**
