### PR TITLE
Support vscode extensions

### LINKED ISSUE #14: Feature Request: Vscode extensions
It would be super helpful if nvfetcher could manager vscode extensions. [Here is how nixos updates vscodes extensions](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vscode-extensions/update_installed_exts.sh)

I think the toml would look like 

```toml
[myextension]
src.vscodeMarketplace = "publisher.name"
fetch.vscodeMarketplace = "publisher.name"

[myextension2]
src.openVSX = "publisher.name"
fetch.openVSX = "publisher.name"
```

and would produce

```nix
Using vscode Marketplace
  {
    myextension = {
    pname = "myextension";
    name = "LiveServer";
    publisher = "ritwickdey";
    version = "5.6.1";
    src = fetchurl {
      sha256 = "077arf3hsn1yb8xdhlrax5gf93ljww78irv4gm8ffmsqvcr1kws0";
      url = "https://ritwickdey.gallery.vsassets.io/_apis/public/gallery/publisher/ritwickdey/extension/LiveServer/5.6.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
    };

  };
Using OpenVSX
  {
    myextension2 = {
    pname = "myextension2";
    name = "LiveServer";
    publisher = "ritwickdey";
    version = "5.6.1";
    src = fetchurl {
      sha256 = "1hzk5g7m3mvgi5jyv3xfw6q8rz21vwa1r1a8f8iik9pgma3pkymq";
      url = "https://open-vsx.org/api/ritwickdey/LiveServer/5.6.1/file/ritwickdey.LiveServer-5.6.1.vsix";
    };

  };
```

I have created a simple and poorly written (but functional) shell script to demonstrate the URLs nvfetcher would need to use to get versions and extensions.

```shell
#! /usr/bin/env nix-shell
#! nix-shell -i bash -p curl jq
set -eu -o pipefail

# Helper to just fail with a message and non-zero exit code.
function fail() {
    echo "$1" >&2
    exit 1
}

# Helper to clean up after ourselves if we're killed by SIGINT.
function clean_up() {
    TDIR="${TMPDIR:-/tmp}"
    echo "Script killed, cleaning up tmpdirs: $TDIR/vscode_exts_*" >&2
    rm -Rf "$TDIR/vscode_exts_*"
    rm -Rf "$TDIR/openVSX_*"
}

function mkSourceGenerated() {
    cat <<-EOF
  {
    $1 = {
    pname = "$1";
    name = "$2";
    publisher = "$3";
    version = "$4";
    src = fetchurl {
      sha256 = "$5";
      url = "$6";
    };

  };
EOF
}

function vscodeGetVersion() {
    if [ ! -z $1 ] && [ ! -z $2 ]; then
        publisher=$1
        extName=$2
        read -r -d '' jsonPayload << EOJ
{
   "filters":[
      {
         "criteria":[
            {
               "filterType":8,
               "value":"Microsoft.VisualStudio.Code"
            },
            {
               "filterType":10,
               "value":"${publisher}.${extName}"
            },
            {
               "filterType":12,
               "value":"4096"
            }
         ],
         "pageNumber":1,
         "pageSize":2,
         "sortBy":0,
         "sortOrder":0
      }
   ],
   "assetTypes":[
      
   ],
   "flags":946
}
EOJ
        paramsArr=(
            "-H 'Accept: application/json;api-version=6.1-preview.1'"
            "-H 'Referer: '"
            "-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.51.0 Chrome/83.0.4103.122 Electron/9.3.3 Safari/537.36'"
            "-H 'X-Market-Client-Id: VSCode 1.51.0'"
            "-H 'Content-Type: application/json'"
            "--data-binary '${jsonPayload}'"
            "--compressed"
        )

        params=$(printf "'%s' \\" "https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery") 
        for arg in "${paramsArr[@]}"; do
            if [ "$arg" = "${paramsArr[-1]}" ]; then
                params=$(printf "%s\n  %s" "${params}" "${arg}")
            else
                params=$(printf "%s\n  %s \\" "${params}" "${arg}")
            fi
        done

        getResp=$(printf "curl --silent --show-error --fail %s\n" "${params}")
        resp=$(eval "${getResp}")
        version=$(echo "${resp}" | jq -r '.results[0].extensions[] | {version: .versions[0].version}' | awk '{print $2}' | sed 's/"//g' )
        echo $version
    elif [ ! -z $1]; then
        fail "Forgot extension name"
    else
        fail "Forgot publisher and extension name"
    fi
}

function getExtension() {
    if [ ! -z $1 ] && [ ! -z $2 ] && [ ! -z $3 ]; then
        publisher=$1
        extName=$2
        pname=$3
        # Will use OpenVSX if provided 4 arguements
        if [ $# == 4 ]; then
            version=$(curl --silent --show-error --fail https://open-vsx.org/api/${publisher}/${extName} | jq  .version | sed 's/"//g')
            URL="https://open-vsx.org/api/${publisher}/${extName}/${version}/file/${publisher}.${extName}-${version}.vsix"
            EXTTMP=$(mktemp -d -t openVSX_XXXXXXXX)
        else
            version=$(vscodeGetVersion ${publisher} ${extName})
            EXTTMP=$(mktemp -d -t vscode_exts_XXXXXXXX)
            URL="https://${publisher}.gallery.vsassets.io/_apis/public/gallery/publisher/${publisher}/extension/${extName}/${version}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage"
        fi
        vsixFile="${publisher}.${extName}-${version}.vsix"

        # Quietly but delicately curl down the file, blowing up at the first sign of trouble.
        curl --silent --show-error --fail -X GET -o  "${EXTTMP}/${vsixFile}" -L "${URL}"

        sha256=$(nix-hash --flat --base32 --type sha256 "${EXTTMP}/${vsixFile}")
        genNix=$(mkSourceGenerated ${pname} ${extName} ${publisher} ${version} ${sha256} ${URL})

        # Clean up.
        rm -Rf "$EXTTMP"
        # I don't like 'rm -Rf' lurking in my scripts but this seems appropriate.

        printf "$genNix\n"
    elif [ ! -z $1] && [ ! -z $2 ]; then
        fail "Forgot pname"
    elif [ ! -z $1]; then
        fail "Forgot extension name, and pname"
    else
        fail "Forgot publisher, extension name, and pname"
    fi
}

# Try to be a good citizen and clean up after ourselves if we're killed.
trap clean_up SIGINT

getExtension ritwickdey LiveServer myextension
getExtension ritwickdey LiveServer myextension2 "true"
```

**NOTE:** You will have to scroll to view source.

### PR DESCRIPTION
**Pull request by berberman**
Closes #14 

TODO:
* [ ] Pull `publisher` and `name` into nix expr

Now
```toml
[testa]
src.openvsx = "ritwickdey.LiveServer"
fetch.openvsx = "ritwickdey.LiveServer"

[testb]
src.vsmarketplace = "ritwickdey.LiveServer"
fetch.vsmarketplace = "ritwickdey.LiveServer"
```
can produce
```nix
{
  testa = {
    pname = "testa";
    version = "5.6.1";
    src = fetchurl {
      sha256 = "1hzk5g7m3mvgi5jyv3xfw6q8rz21vwa1r1a8f8iik9pgma3pkymq";
      url = "https://open-vsx.org/api/ritwickdey/LiveServer/5.6.1/file/ritwickdey.LiveServer-5.6.1.vsix";
    };
  };
  testb = {
    pname = "testb";
    version = "5.6.1";
    src = fetchurl {
      sha256 = "077arf3hsn1yb8xdhlrax5gf93ljww78irv4gm8ffmsqvcr1kws0";
      url = "https://ritwickdey.gallery.vsassets.io/_apis/public/gallery/publisher/ritwickdey/extension/LiveServer/5.6.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
    };
  };
}
```

### CODE REVIEW

**Comment by berberman** [comment]
Actually I think it's not clear to generate `publisher` and `name` - these two attrs make no sense from the view point of nvchecker and prefetch, whereas they are package (drv) level things which nvfetcher has nothing to do with.

I plan to add a "passthru" option that can splice nix exprs (string) from configuration file (suggested by @NickCao). For example:
```toml
[testa]
src.openvsx = "ritwickdey.LiveServer"
fetch.openvsx = "ritwickdey.LiveServer"
passthru.publisher = "ritwickdey"
passthru.name = "LiveServer"
```
would produce
```nix
  testa = {
    pname = "testa";
    version = "5.6.1";
    src = fetchurl {
      sha256 = "1hzk5g7m3mvgi5jyv3xfw6q8rz21vwa1r1a8f8iik9pgma3pkymq";
      url = "https://open-vsx.org/api/ritwickdey/LiveServer/5.6.1/file/ritwickdey.LiveServer-5.6.1.vsix";
    };
    publisher = "ritwickdey";
    name = "LiveServer";
  };
```
It looks a bit verbose, but I think this is more reasonable. @Th3Whit3Wolf What do you think?

**Comment by Th3Whit3Wolf** [comment]
What is the benefit of putting `passthru.publisher` `passthru.name` as additional options?

`"${passthru.publisher}.${passthru.name}"` will always equal the value of `{src/fetch}.(openvsx/vsc-marketplace} `.

Is it not possible to make this

```toml
[testa]
src.openvsx = "ritwickdey.LiveServer"
fetch.openvsx = "ritwickdey.LiveServer"
```

produce this?

```nix
 testa = {
    pname = "testa";
    version = "5.6.1";
    src = fetchurl {
      sha256 = "1hzk5g7m3mvgi5jyv3xfw6q8rz21vwa1r1a8f8iik9pgma3pkymq";
      url = "https://open-vsx.org/api/ritwickdey/LiveServer/5.6.1/file/ritwickdey.LiveServer-5.6.1.vsix";
    };
    publisher = "ritwickdey";
    name = "LiveServer";
  };
```

**Comment by berberman** [comment]
> What is the benefit of putting `passthru.publisher` `passthru.name` as additional options?

No benefit at all here, though passthru has other use cases.

> `"${passthru.publisher}.${passthru.name}"` will always equal the value of `{src/fetch}.(openvsx/vsc-marketplace} `.
> 
> Is it not possible to make this
> 
> ```toml
> [testa]
> src.openvsx = "ritwickdey.LiveServer"
> fetch.openvsx = "ritwickdey.LiveServer"
> ```
> 
> produce this?
> 
> ```nix
>  testa = {
>     pname = "testa";
>     version = "5.6.1";
>     src = fetchurl {
>       sha256 = "1hzk5g7m3mvgi5jyv3xfw6q8rz21vwa1r1a8f8iik9pgma3pkymq";
>       url = "https://open-vsx.org/api/ritwickdey/LiveServer/5.6.1/file/ritwickdey.LiveServer-5.6.1.vsix";
>     };
>     publisher = "ritwickdey";
>     name = "LiveServer";
>   };
> ```

The question is that it's not clear when we should generate these two attrs. Consider the following examples:

1. We fetch the source from other places
```toml
[testa]
src.openvsx = "ritwickdey.LiveServer"
fetch.url = "https://github.com/ritwickdey/vscode-live-server/releases/download/v$ver/LiveServer-v$ver-linux.vsix"
```

2. We pin its version
```toml
[testa]
src.manual = "5.6.1"
fetch.openvsx = "ritwickdey.LiveServer"
```

Then should we have `publisher` and `name` in results? It turns out that generating them is an *orthogonal* feature -  two attrs are used in the follow-up drv building, which is unrelated to nvfetcher.

**Comment by Th3Whit3Wolf** [comment]
> Then should we have publisher and name in results? It turns out that generating them is an orthogonal feature - two attrs are used in the follow-up drv building, which is unrelated to nvfetcher.

I think so, in both cases

```nix
publisher = "ritwickdey";
name = "LiveServer";
```

are correct. I don't see any issues with having a pass through either though.

**Pull request merged**
