### PR TITLE
support sparseCheckout

### PR DESCRIPTION
**Pull request by wrvsrx**

### CODE REVIEW

**Comment by berberman** [comment]
Can you add an example in `nvfetcher_example.toml`? And a unit test would be even better.

**Comment by wrvsrx** [comment]
Sure, I'll do that later.

**Comment by wrvsrx** [comment]
I have added an example and fix the failure test related to this PR.  @berberman

**Review by berberman — APPROVED** [review]
Sorry for the late response; thank you!

**Pull request merged**
